name: telegram-oai-workshop
channels:
  - default
dependencies:
  - pip=23.1.2
  - python=3.9
  - pip:
    - python-dotenv==1.0.0
    - pyTelegramBotAPI==4.12.0
    - langchain==0.0.305
    - openai==0.28.1